# SPDX-FileCopyrightText: 2022 Winni Neessen <winni@neessen.dev>
#
# SPDX-License-Identifier: MIT

freebsd_task:
  name: FreeBSD

  matrix:
    - name: FreeBSD 13.1
      freebsd_instance:
        image_family: freebsd-13-1
    - name: FreeBSD 12.4
      freebsd_instance:
        image_family: freebsd-12-4
    - name: FreeBSD 12.3
      freebsd_instance:
        image_family: freebsd-12-3

  env:
    TEST_ALLOW_SEND: 0

  pkginstall_script:
    - pkg update -f
    - pkg install -y go postfix

  test_script:
    - go test -v -race -cover -shuffle=on ./...