# SPDX-FileCopyrightText: 2022 Winni Neessen <winni@neessen.dev>
#
# SPDX-License-Identifier: CC0-1.0

coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 5%
        base: auto 
        if_ci_failed: error
        only_pulls: false
    patch:
      default:
        target: 80%
        base: auto
        if_ci_failed: error
        threshold: 5%

comment:
  require_changes: true
